apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodeapp-data
  namespace: mongo-express-prometheus-grafana
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/nodeapp-data