apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: mongo-express-prometheus-grafana
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/prometheus-data