apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prometheus-pvc
  namespace: mongo-express-prometheus-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
