apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: mongo-express-prometheus-grafana
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 80
    targetPort: 9090
    nodePort: 30000