apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: mongo-express-prometheus-grafana
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001
  selector:
    app: mongo-express-deployment

